In [1]:
# numpy array operations
import numpy as np

In [8]:
# Datatype conversion(flot to int)
a=np.array([1.1,2.8,3.0,4.5])
b=a.astype(int)

print("float array=",a)
print("int array=",b)
b.dtype

float array= [1.1 2.8 3.  4.5]
int array= [1 2 3 4]


dtype('int32')

In [9]:
# Datatype conversion(binary to boolean)
a=np.array([1,0,0,0,1])
b=a.astype(bool)

print("binary array=",a)
print("boolean array=",b)

binary array= [1 0 0 0 1]
boolean array= [ True False False False  True]


In [11]:
# transpose of a matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.transpose()

print("original matrix\n",a)
print("\nmatrix after transpose\n",b)

original matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix after transpose
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
# Sorting array and printing the sorted element indexes
a=np.array([3,7,4,2,9,1])
b=np.argsort(a)
print("original matrix\n",a)
print("\nsorted array indexes\n",b)

original matrix
 [3 7 4 2 9 1]

sorted array indexes
 [5 3 0 2 1 4]


In [2]:
# sum of the 2 numpy arrays
a=np.array([[2,4,6],[1,7,9]])
b=np.array([[15,44,61],[11,81,0]])

c=np.add(a,b)

print("a\n",a)
print("\nb\n",b)
print("\nmatrix after addition\n",c)

a
 [[2 4 6]
 [1 7 9]]

b
 [[15 44 61]
 [11 81  0]]

matrix after addition
 [[17 48 67]
 [12 88  9]]


In [3]:
# scalar multiplication
a=np.array([[2,4,6],[1,7,9]])

b=a*4

print("original matrix\n",a)
print("\nmatrix after scalar multiplication\n",b)


original matrix
 [[2 4 6]
 [1 7 9]]

matrix after scalar multiplication
 [[ 8 16 24]
 [ 4 28 36]]


In [4]:
# 1-D array to a 3-D array
a=np.array([2,4,6,2,1,8,5,9,5,10,11,12])

b=a.reshape(2,3,2)

print('1-D array\n',a)
print('\n3-D array\n',b)

1-D array
 [ 2  4  6  2  1  8  5  9  5 10 11 12]

3-D array
 [[[ 2  4]
  [ 6  2]
  [ 1  8]]

 [[ 5  9]
  [ 5 10]
  [11 12]]]


In [5]:
# printing the indexes in which the elements in the 2 arrays match
a=np.array([2,4,6,2,1,8,5,9,5,10,11,12])
b=np.array([2,9,1,0,1,2,7,1,4,10,1,2])

c=np.where(a==b)

print('array 1\n',a)
print('\narray 2\n',b)
print("\nmatching indexes:",c)

array 1
 [ 2  4  6  2  1  8  5  9  5 10 11 12]

array 2
 [ 2  9  1  0  1  2  7  1  4 10  1  2]

matching indexes: (array([0, 4, 9], dtype=int64),)


In [6]:
# views and copy of numpy
a=np.array([2,4,6,2,1,8,5])
b=a.copy()
a[2]=12
print("original array after assigning to original",a)
print("copy array after assigning to original",b)

c=b.view()
b[2]=12
print("\ncopy array after assigning to copy",b)
print("view array after assigning to copy",c)

original array after assigning to original [ 2  4 12  2  1  8  5]
copy array after assigning to original [2 4 6 2 1 8 5]

copy array after assigning to copy [ 2  4 12  2  1  8  5]
view array after assigning to copy [ 2  4 12  2  1  8  5]


In [7]:
# Even elements in an array, elements greater than 10 in an array 
a=np.array([2,4,6,2,1,8,5,9,5,10,11,12])
even=[]
for i in a:
    if(i%2==0):
        even.append(i)
print("even elements:",even)

g_10=[]
for i in a:
    if(i>10):
        g_10.append(i)
print("\nelements > 10:",g_10)


even elements: [2, 4, 6, 2, 8, 10, 12]

elements > 10: [11, 12]
